### ISSUE TITLE
I can't get cquery ide to work

### ISSUE THREAD

**Issue by dpriedel** [rianneogi/ide-cquery#10]
Hi

I am having a problem getting the ide-cquery package to work with atom.  I have the atom IDE working fine with the ide-python package so I know I have the basics working.

I have cquery installed and the atom ide-cquery package. I have clang installed too.  I can start cquery from the command line (I am running on Manjaro Linux).
When I open a C++ file in my project, nothing happens.  For example, if I try to open the Outline view, atom says I need to install an IDE package first. I get no completion suggestions.

When I have a Python file open in atom, I see a pyls process running on my system.  When i have a C++ file open (filename ends with .cpp), I do not see a cquery process running. Atom does recognize the file as C++ as indicated by status bar at the bottom of the editor window.

I'm pretty sure I'm missing something basic here...

I'm running atom 1.25.0

Thanks for any help

Dave

**Comment by rianneogi** [comment]
Hi,
If you go to ide-cquery settings -> Enable logging, a log file called will
be created at your project root.
Can you upload it's contents?

**Comment by dpriedel** [comment]
Hi

I did as you suggested and ... no log file created.  It's as if atom doesn't know it should be activating this plug-in.  There are no messages in the developer console either.

So, I quit atom, renamed my .atom folder, restarted atom and installed just the atom-ide-ui and cquery-ide plug-ins.  Everything works!! 

So, there appears to be a package conflict. I will try to track that down.  I will post what I find.

Thanks

Dave

**Comment by dpriedel** [comment]
I think I have found what triggers the problem.  When I have 'use tree sitter parsers' enabled, then the ide-cquery package is not active.  If I disable that setting, then ide-cquery works.

I have restored my original .atom folder and turned off the tree sitter parsers.  Everything works !!

Dave

**Comment by rianneogi** [comment]
Great!
