### ISSUE TITLE
Allow additional cquery arguments

### ISSUE THREAD

**Issue by kc9jud** [rianneogi/ide-cquery#14]
cquery takes additional arguments, for instance for scrubbing bad flags from `compile_commands.json`. It would be helpful to be able to provide them somehow.

See https://github.com/cquery-project/cquery/issues/419 and https://github.com/cquery-project/cquery/wiki/compile_commands.json#stdout-of-an-external-command

**Comment by edjubuh** [comment]
#7 added extraClangFlags as an option. It should be straightforward to do
the same thing for this option.
