### ISSUE TITLE
Namespace completion

### ISSUE THREAD

**Issue by BigfootN** [rianneogi/ide-cquery#19]
Hello,

Everything works just fine. The only problem, is then when I write for example:
```C++
void* <namespace>::
```
it doesn't suggest the underlying namespace or class, even with `ctrl+space`. I have to start writing it to have a suggestion.

Thank you very much in advance.

**Comment by rianneogi** [comment]
Change 'Minimum Word Length' to 0 in Autocomplete+ plugin settings. This seems to fix the issue for me.
