### ISSUE TITLE
Problem with CamelCase folders and names.

### ISSUE THREAD

**Issue by nicoberrogorry** [rianneogi/ide-cquery#20]
**Bug or feature? Or even my own ignorance?**
Diagnostics emits erros for my files, but some of them appear as lowercase when they're actually CamelCase! Even the paths are lowercase... I'm lucky windows doesn't notice!
Even hyperclick opens the files with lowercase path's and file names...

**Capture**
![image](https://user-images.githubusercontent.com/19650927/43056389-76bd2dc8-8e12-11e8-9f91-b66c11f9bea0.png)

**Personal Context**
I know it's a good practice to develop c++ in lowercase folders with lowercase files, but that's a matter of portability... I'm developing a very simple project for my Uni and its only for windows, and my teammates which come from other languages find it horrible to code in lowercase, so CamelCase is a must.

By the way this plugin is the best that happened to me in a long time, exaggerations aside!

**Comment by nicoberrogorry** [comment]
This should be closed, but kept here for anyone who clashes with this bug.

** This is how I fixed it! **

Ok so this is not a bug of this plugin, its an incompatibility of CQuery and Windows due to the case insensitive nature of the OS. To fix get full compatibility I modified my system with the following steps, which are an approximation because I'm not on my dev machine right now.

- Installed Windows Subsystem for Linux on my Windows 10 Developer machine.
- I enabled case sensitivity for NTFS recursively via PowerShell on my repositories folder (this was a professional choice for my development environment, you can do this only for the project giving you trouble or whatever you want, actually, im not responsible in any way!
- I added a line to CQuery's function NormalizePath(..., bool lowercasePathOnWindows) to override the "lowercase" parameter to false! (lowercase = false...)

I know this is very hackish, but it's working like a charm for me!

Have a good one.

**Comment by rianneogi** [comment]
Alright, closing!
