### ISSUE TITLE
Semantic highlighting and inactive regions not working

### ISSUE THREAD

**Issue by NexAdn** [rianneogi/ide-cquery#21]
Running Arch with cquery-git `1947.af7f14cc` (from AUR) and clang/llvm both `6.0.1`.

Diagnostics, code completion etc. are all working fine, the compilation database seems to be used correctly, too; only semantix syntax highlighting is not working at all. Looking at Atom's HTML code the elements aren't even sourrounded by a `span` element with the appropriate cquery syntax class, but instead just with the standard syntax highlighting classes. The console gives me this:

```
XXXXXXXXXXXX (censored)
```
ide-cquery settings:
* Cquery Path: `/usr/bin/cquery` (exists)
* (X) Discover System Includes
* (X) Enable Semantic Highlighting
* (X) Enable Set Inactive Regions
* Initialization Options Cache Format: Serialize in JSON format
* (X) Initialization Options client Snippet Support
* (X) Initialization Options Completion Detailed Label
* (X) Initialization Options Diagnostics On Parse
* (X) Initialization Options Enable Index On Did Change
* (X) Initialization Options Index Attribute Make Call To Ctor
* Initialization Options Index Comment Parsing: All comments
* (X) Initialization Options Index Enabled
* ( ) Initialization Options Index Log Skipped Paths
* (X) Initialization Options Workspace Symbol Sort
* ( ) Initialization Options Xref Container
* ( ) Logging
All settings not mentioned are either empty or default.

The stylesheet has been edited and all cquery classes inserted properly (as in the example styles.less from README).

**Comment by rianneogi** [comment]
I patched a potential fix just now. Please update ide-cquery and check if it works now.

**Comment by NexAdn** [comment]
Nice, everything is working fine now. Thank you very much.
