### ISSUE TITLE
error after most recent update

### ISSUE THREAD

**Issue by KaiFish** [rianneogi/ide-cquery#22]
since updating (through atom) I have been getting "cquery language server for C++ unable to start
Error: spawn cquery ENOENT" I am not sure if this is my own fault or not, so any help would be appreciated.

**Comment by rianneogi** [comment]
Hi,
Can you update your cquery to the latest [release build](https://github.com/cquery-project/cquery/releases) and try?

**Comment by KaiFish** [comment]
Seems to have fixed it! Thanks!
