### ISSUE TITLE
Thanks so much

### ISSUE THREAD

**Issue by jasikpark** [rianneogi/ide-cquery#25]
Thank you for being the only cpp languageserver package for atom-ide that I could find that actually works and integrates well. I really wanted to use ide-c-cpp because it supported `ccls` which seemed like it should be better, but this works great (for the two seconds that it's been working)

Thank you.

**Comment by rianneogi** [comment]
No problem. The reason I created this is because none of the other ide packages seemed to provide all the facilities when I wanted to code in C++. I wanted a Visual Studio replacement for Linux and cquery was the best I found.
.
