### ISSUE TITLE
preprocessor directives autocompletion messed up

### ISSUE THREAD

**Issue by junee455** [rianneogi/ide-cquery#26]
Hello, I have an issue here
cquery autocompletes any preprocessor directive with two hashes. I type, say #inc, cquery suggests #include but after I press enter I get ##include.
After removing extra hash, cquery tries to help me with library names, but instead of this
#include \<libName\>
I get this
#include \<#include \<libName\>

I've disabled Atom's native snippet support and cquery snippets both, but it didn't help
Help please
![cquery bug](https://user-images.githubusercontent.com/22997044/51855235-cfee7800-233d-11e9-957b-01ad085f1a1d.gif)

**Comment by fargies** [comment]
Hello,

I've been experiencing the exact same issue for a while, can you please comment the way to fix this ?

**Comment by rianneogi** [comment]
The problem is with the atom-languageclient dependency. See here https://github.com/atom/atom-languageclient/issues/220
