### ISSUE TITLE
 My English is so bad that I can't understand how to install cquery Language Server

### ISSUE THREAD

**Issue by 3038922** [rianneogi/ide-cquery#4]
~.~ I hope ATOM can complete the compilation of PYTHON ,C ,C++.
cquery Language Server 's' help is too difficult to understand.

**Comment by rianneogi** [comment]
You need to install [atom-ide-ui](https://atom.io/packages/atom-ide-ui) package.
Then download [cquery](https://github.com/jacobdufault/cquery) and build it.
(To build cquery open terminal/cmd in cquery folder and type 'python waf configure' then 'python waf build')

**Comment by 3038922** [comment]
Q1:
NCRserver@NCRServer MINGW64 ~
$ git clone https://github.com/jacobdufault/cquery --single-branch --depth = 1
fatal: depth = is not a positive number
Q2:
Failed to find MSBuild toolsets directory
Do I have to install VS?


![image](https://user-images.githubusercontent.com/33926386/34923300-9ffda806-f9d5-11e7-8669-2ee7bd380025.png)

**Comment by 3038922** [comment]
Excuse me .I don't know why.

**Comment by 3038922** [comment]
(To build cquery open terminal/cmd in cquery folder and type 'python waf configure' then 'python waf build')

python waf configure ?i want use c or c++

**Comment by phord** [comment]
@3038922 I think you need to remove the spaces around the "=" in your git clone command.
`git clone https://github.com/jacobdufault/cquery --single-branch --depth=1`
