### ISSUE TITLE
code completion insert extra $0 $1 s

### ISSUE THREAD

**Issue by ProgramFan** [rianneogi/ide-cquery#5]
When using cquery trunk with atom 1.23.2 on macOS 10.13.2, the code completion insert extra $0 $1 in the editor, for example:

```cpp
std::vector<int> test;
test.at|Tab
==> test.at($1)$0
```

**Comment by rianneogi** [comment]
Yes, this is a bug in the cquery language server.

I will try to forward this issue to the cquery team.

**Comment by ProgramFan** [comment]
I actually tested it on VSCode and it turned out to output a snippet which is then expanded. Don't understand why they choose to do this.

**Comment by jacobdufault** [comment]
Atom should be inserting snippets, when I looked it up in the past [autocomplete-plus](https://github.com/atom/autocomplete-plus) has snippet support, so ideally ide-cquery implements snippet support. Right now it turns off cquery support for snippets (so cquery should not be emitting any $ placeholders).

**Comment by rianneogi** [comment]
You can switch on snippet insertion in the ide-cquery settings.
But when snippet insertion is off, cquery should not be adding $ signs.

**Comment by ProgramFan** [comment]
When the snippet insertion is on, I got the following outputs:
```cpp
name.append(${1:const std::basic_string<char> &__str})$0
```
for functions with arguments. Are there extra settings I need to take care of?

**Comment by ProgramFan** [comment]
Digging more into the issue, I found that the completions returned by cquery is not tagged as "snippet", so the snippet triggers are not invoked. This can hopefully be handled in ide-cquery when the user specifies to handle completions as snippets. :smile:

**Comment by jacobdufault** [comment]
It'd be really appreciated if you submit a PR so ide-cquery recognizes the snippets :), or is it a change needed on cquery side?

**Comment by rianneogi** [comment]
Fixed after updating the dependencies (new patch)
