### ISSUE TITLE
Make use of atom-ide-busy-signal

### ISSUE THREAD

**Issue by maximeB** [rianneogi/ide-cquery#6]
It would be very handy to know when cquery is running and when it's done.

Also applies to outline-view. Currently when cquery is not done parsing, the outline-view is shown as unavailable with the following message:
![image](https://user-images.githubusercontent.com/2788250/36934442-b8900966-1ee9-11e8-8e52-766724e754bb.png)

Versions:
Atom:          1.24.0
atom-ide-ui: 0.9.2
ide-cquery:  0.5.0

**Comment by rianneogi** [comment]
Its something that needs to be done on atom-ide-ui's side. Are there any other ide packages that do this?

**Comment by maximeB** [comment]
It seemed to be doing it with ide-typescript. But I looked at the code, I don't understand how...

Still there seems to be a busy-signal part in atom-ide-ui, I'm sure we could use it, at least to specify that cquery is running.

**Comment by rianneogi** [comment]
Added in new patch
